"""create category

Revision ID: c32dc41e93a2
Revises: 23f332a81baf
Create Date: 2023-04-17 17:45:39.042734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32dc41e93a2'
down_revision = '23f332a81baf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('trx_type', sa.Column('category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trx_type', 'category', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trx_type', type_='foreignkey')
    op.drop_column('trx_type', 'category')
    op.drop_table('category')
    # ### end Alembic commands ###
