"""change  category

Revision ID: f5d153a21f34
Revises: c32dc41e93a2
Create Date: 2023-04-18 13:12:56.875918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d153a21f34'
down_revision = 'c32dc41e93a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('money', sa.Column('category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'money', 'category', ['category'], ['id'])
    op.drop_constraint('trx_type_category_fkey', 'trx_type', type_='foreignkey')
    op.drop_column('trx_type', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trx_type', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('trx_type_category_fkey', 'trx_type', 'category', ['category'], ['id'])
    op.drop_constraint(None, 'money', type_='foreignkey')
    op.drop_column('money', 'category')
    # ### end Alembic commands ###
